branch-defaults:
  master:
    environment: Bugcide-env-prod
environment-defaults:
  Bugcide-env-prod:
    branch: null
    repository: null
global:
  application_name: bugcide
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Node.js running
    on 64bit Amazon Linux/4.11.0
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
